### ISSUE TITLE
project based/multi-files edit history

### ISSUE THREAD

**Issue by erinata** [Stuk/sublime-edit-history#3]
The plugin is working great. However would it be possible to use one edit history cross all the opened files?

**Comment by Stuk** [comment]
Would you like only global (per window) edit history, or would you like to combine local (file) and global history? I thought about the later and couldn't think of a conceptual way for it to work, but the former should be possible.

**Comment by erinata** [comment]
For me, I only like to have per window (or per project)  edit history. But of course I understand that other people may need a local file one.

**Comment by Stuk** [comment]
Cool. I'll see about making it an option to have either file or global history.

**Comment by titoBouzout** [comment]
I think would be better to have both at the same time. 
For example "ALT back" will back in global history, "back" will back in file history.
Not sure how complex this can be.

**Comment by Stuk** [comment]
If you can come up with a concept that works that would be great. 

The problem I came into was this:

You have two files, file A, and file B. Their history looks like this:

**A** _Back_: A1, _Current_: A2, _Forward_: A3
**B** _Back_: B1, _Current_: B2, _Forward_: B3

The global history looks like this:

**G** _Back_: A1, B1, B2, _Current_: A2, _Forward_: B3

You then do a global back:
Local histories stay the same
**G** _Back_: A1, B1, _Current_: B2, _Forward_: A2, B3

You then do a local forward:
A remains the same
**B** _Back_: B1, B2, _Current_: B3, _No forward_

What does **G** look like? Should pressing forward take you to A2 still, or does the the Forward stack get wiped out whenever you do any non-global navigation?

What do you guys think? (This is hard to explain, so let me know if the example isn't clear)

It's much easier to have a toggle between only local, or only global history.

**Comment by erinata** [comment]
I think you explain very clearly. Before I throw in my idea, let me say it again if I have a vote, I would vote of Global history only :P   But if we really need to incorporate both, I would suggest the following.
1. Keep only a Global History
2. A Global forward/backward means a ONE step forward/backward
3. A Local forward/backwards mean an X step forward/backward in GLOBAL history, where X >= 1 

using your example, 

At the very beginning, we have 
_G_ Back: A1, B1, B2, Current: A2, Forward: B3, A3      (I thought you accidentally missed the A3 in your example)

and we IGNORE the local.

When we do a global back, we jump back ONE step
_G_ Back: A1, B1, Current: B2, Forward: A2, B3, A3

When we do a local forward, use the global history and find the next step in document B
_G_ Back: A1, B1, B2, A2 Current: B3, Forward:  A3

And suppose we do a global back
_G_ Back: A1, B1, B2 Current: A2 Forward:  B3, A3

And then a local foward
_G_ Back: A1, B1, B2, A2, B3 Current: A3, Forward: none

The the history is still the same GLOBAL history and there is only ONE history to maintain.

**Comment by erinata** [comment]
I think the real challenge is, how do we deal with the history erasing. The situation become quite complicated as we need to deal with "what (local) history should we erase when someone add a new step in the middle of the history.

Here is what I think.
1. When someone add a new step in the history, erase all forward step in the GLOBAL history which is in the same document as the current document
2. And yes, I can just say erase all forward step in the LOCAL history. But as I mentioned in the previous comment, my model only deal with one GLOBAL history. so ignore the LOCAL
   
   ---

Example:

Suppose we have a history of 

G Back: A1, B1, B2, Current: A2, Forward: B3, A3

we do a global back, 

G Back: A1, B1, Current: B2 Forward: A2, B3, A3

And we edit somewhere in document B to at a edit step B4. In this case all forward step in the GLOBAL history or document B is erased.

G Back: A1, B1, Current: B4 Forward: A2, A3

But the document A history is still here. So we can still do a GLOBAL forward

G Back: A1, B1, B4 Current: A2 Forward: A3

---

Another Example:

Suppose we have 
G Back: A1, B1, B2, Current: A2, Forward: B3, A3

we do a global back, 

G Back: A1, B1, Current: B2 Forward: A2, B3, A3

And now I change tab to document A without editing document B, and edit something in document A to form a new step A4. The GLOBAL history will become

G Back: A1, B1, B2 Current: A4 Forward: B3

Notice that B2 is pushed to the BACK of A4. As a rule, 
1. when we are editing a document which is the same as the document of current step, we erase the current step.
2. But if we are editing a document which is different from the document of current step, we push the current step to the BACK
   
   ---

This is obviously not the only way to model this thing up. And I still think there's a lot of problems. But hopefully the discussion helps.

**Comment by zuthan** [comment]
I think it would be very difficult to merge global and local history so that it behaves in an intuitive way. When I try to figure out what I would expect to happen if I go forward in the global history after making an edit I find that I simply can't conceive a conceptual model with which to make a prediction. Local and global history behaviour each have an intuitive conceptual model on their own so providing users with a setting to chose between them would certainly be acceptable, but I don't think the two can be combined without causing confusion.

There may be a way to augment local history behaviour, though, so that global navigation of the edit history is still possible in an intuitive way. What I have in mind is a view-level (as opposed to text level) history navigation function. Let's provisionally call the functions previous_view_edit and next_view_edit. previous_view_edit would take you to the last view in which you made an edit and move the cursor to the last edit location stored for that view. You could then use local edit navigation within that view without interfering with the view-level edit history. Making an edit would clear the next history at both local and view-level.

I think this model would be intuitive for most people to understand since it just applies the same conceptual model of edit history they are already used to two different basic actions: text editing and view editing. It also has the added advantage that it would be easy to implement since the existing logic can be almost completely reused.

**Comment by matamouros** [comment]
I'm guessing this was thrown to the side because ST3 already has it, right?

**Comment by Stuk** [comment]
Yep, I'm not planning on personally working on this plugin further.

**Comment by matamouros** [comment]
Sure, thanks! (Maybe you can close the issue?) Cheers.
